language: java

jdk: openjdk8
sudo: true
install: true

services:
  - docker

before_install:
  - chmod +x mvnw

script: 
  - ./mvnw clean install
  
after_install:
  - docker image build --build-arg JAR_FILE=target/twitter-api.jar --tag thomasdacosta/twitter-api:snapshot .
  - docker push thomasdacosta/twitter-api:snapshot

cache:
  directories:
  - $HOME/.m2
