language: java

jdk: openjdk8
sudo: true
install: true

services:
  - docker

before_install:
  - chmod +x mvnw

script: 
  - ./mvnw clean install
  - docker image build --build-arg JAR_FILE=target/twitter-api.jar --tag thomasdacosta/twitter-api:snapshot $TRAVIS_BUILD_DIR/twitter-api
  - docker push thomasdacosta/twitter-api:snapshot
  - docker image build --build-arg JAR_FILE=target/twitter-consumer.jar --tag thomasdacosta/twitter-consumer:latest $TRAVIS_BUILD_DIR/twitter-consumer
  - docker push thomasdacosta/twitter-consumer:latest
  - echo $TRAVIS_BUILD_DIR

cache:
  directories:
  - $HOME/.m2
