language: java

jdk: openjdk8
sudo: true
install: true

services:
  - docker

before_install:
  - chmod +x mvnw

script: 
  - ./mvnw clean install
  - docker image build --build-arg JAR_FILE=twitter-api/target/twitter-api.jar --tag thomasdacosta/twitter-api:snapshot .
  - docker push thomasdacosta/twitter-api:snapshot
  - docker image build --build-arg JAR_FILE=twitter-consumer/target/twitter-consumer.jar --tag thomasdacosta/twitter-consumer:latest .
  - docker push thomasdacosta/twitter-consumer:latest

cache:
  directories:
  - $HOME/.m2
