language: java

jdk: openjdk8
sudo: true
install: true

services:
  - docker

before_install:
  - chmod +x mvnw

script: 
  - ./mvnw clean install
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build --build-arg JAR_FILE=target/twitter-api.jar --tag thomasdacosta/twitter-api:development $TRAVIS_BUILD_DIR/twitter-api
  - docker push thomasdacosta/twitter-api:development
  - docker image build --build-arg JAR_FILE=target/twitter-consumer.jar --tag thomasdacosta/twitter-consumer:development $TRAVIS_BUILD_DIR/twitter-consumer
  - docker push thomasdacosta/twitter-consumer:development

cache:
  directories:
  - $HOME/.m2
