version: '3.2'
services:
  db:
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes --requirepass twitterdemo
    volumes:
      - "db_data:/data"
  consumer:
    image: thomasdacosta/twitter-consumer:latest
    depends_on:
      - db
  api:
    image: thomasdacosta/twitter-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - consumer
volumes:
    db_data: